latihan_laravel-vue/library/routes/web.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
})->middleware('guest');

Auth::routes();

Route::group(['middleware' => 'auth'], function () {
    Route::get('/home', [AdminController::class, 'index']);

    Route::resource('/authors', AuthorController::class);
    Route::resource('/books', BookController::class);
    Route::resource('/catalogs', CatalogController::class);
    Route::resource('/members', MemberController::class);
    Route::resource('/publishers', PublisherController::class);
    Route::resource('/transactions', TransactionController::class);

    Route::get('/api/authors', [AuthorController::class, 'api']);
    Route::get('/api/publishers', [PublisherController::class, 'api']);
    Route::get('/api/members', [MemberController::class, 'api']);
    Route::get('/api/books', [BookController::class, 'api']);
    Route::get('/api/transactions', [TransactionController::class, 'api']);

    Route::get('/test_spatie', [AdminController::class, 'test_spatie']);
});

latihan_laravel-vue/library/app/Models/Publisher.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Publisher extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'email',
        'phone_number',
        'address'
    ];

    public function books()
    {
        return $this->hasMany(Book::class);
    }
}

latihan_laravel-vue/library/app/Http/Controllers/PublisherController.php
<?php

namespace App\Http\Controllers;

use App\Models\Publisher;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class PublisherController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $publishers = Publisher::with('books')->get();
        return view('admin.publisher', compact('publishers'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'name'  => 'required',
            'email' => 'required|email|unique:publishers',
            'phone_number' => 'required',
            'address' => 'required',
        ]);

        if ($validator->fails()) {
            return response()->json($validator->errors(), 422);
        } else {
            Publisher::create([
                'name'   => $request->name,
                'email'   => $request->email,
                'phone_number'   => $request->phone_number,
                'address'   => $request->address,
            ]);

            return response()->json([
                'success'   => true,
                'message' => 'Data Saved Successfully!'
            ]);
        }
    }

    /**
     * Display the specified resource.
     */
    public function show(Publisher $publisher)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Publisher $publisher)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Publisher $publisher)
    {
        $validator = Validator::make($request->all(), [
            'name'  => 'required',
            'email' => 'required|email|unique:publishers,email,' . $publisher->id,
            'phone_number' => 'required',
            'address' => 'required',
        ]);

        if ($validator->fails()) {
            return response()->json($validator->errors(), 422);
        } else {
            $publisher->update([
                'name'   => $request->name,
                'email'   => $request->email,
                'phone_number'   => $request->phone_number,
                'address'   => $request->address,
            ]);

            return response()->json([
                'success'   => true,
                'message' => 'Data Updated Successfully!'
            ]);
        }
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Publisher $publisher)
    {
        $publisher->delete();

        if ($publisher) {
            return response()->json([
                'status' => 'success'
            ]);
        } else {
            return response()->json([
                'status' => 'error'
            ]);
        }
    }

    public function api()
    {
        $publishers = Publisher::with('books')->get();
        $dataTables = datatables()->of($publishers)->addColumn('date', function ($publisher) {
            return convert_date($publisher->created_at);
        })->addIndexColumn();
        return $dataTables->make(true);
    }
}

latihan_laravel-vue/library/resources/views/admin/publisher/create.blade.php
@extends('layouts.admin')
@section('header', 'Publisher')
@section('content')
<div class="row">
    <div class="col">
        <div class="card border-0 shadow">
            <div class="card-header">
                <h6 class="m-0 font-weight-bold"><i class="fas fa-plus mr-2"></i>Create New Publisher</h6>
            </div>

            <div class="card-body">
                <form action="{{ route('publishers.store') }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <div class="form-group">
                        <label>Name</label>
                        <input type="text" name="name" value="{{ old('name') }}"
                            placeholder="Enter Name"
                            class="form-control @error('name') is-invalid @enderror">

                        @error('name')
                        <div class="invalid-feedback" style="display: block">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label>Email</label>
                        <input type="email" name="email" value="{{ old('email') }}"
                            placeholder="Enter Email"
                            class="form-control @error('email') is-invalid @enderror">

                        @error('email')
                        <div class="invalid-feedback" style="display: block">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label>Phone Number</label>
                        <input type="tel" name="phone_number" value="{{ old('phone_number') }}"
                            placeholder="081xxxxxxxxx" pattern="[0-9]{10,14}"
                            class="form-control @error('phone_number') is-invalid @enderror">

                        @error('phone_number')
                        <div class="invalid-feedback" style="display: block">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label>Address</label>
                        <input type="text" name="address" value="{{ old('address') }}"
                            placeholder="Enter Address"
                            class="form-control @error('address') is-invalid @enderror">

                        @error('address')
                        <div class="invalid-feedback" style="display: block">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                    <div class="d-flex justify-content-center">
                        <button class="btn btn-primary mr-1 btn-submit" type="submit"><i class="fa fa-paper-plane"></i>Submit</button>
                        <button class="btn btn-warning btn-reset" type="reset"><i class="fa fa-redo"></i>Reset</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

latihan_laravel-vue/library/resources/views/admin/publisher/edit.blade.php
@extends('layouts.admin')
@section('header', 'Publisher')
@section('content')
<div class="row">
    <div class="col">
        <div class="card border-0 shadow">
            <div class="card-header">
                <h6 class="m-0 font-weight-bold"><i class="fas pencil-alt mr-2"></i>Update Publisher</h6>
            </div>

            <div class="card-body">
                <form action="{{ route('publishers.update', $publisher->id) }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    @method('PUT')
                    <div class="form-group">
                        <label>Name</label>
                        <input type="text" name="name" value="{{ old('name', $publisher->name) }}"
                            placeholder="Enter Name"
                            class="form-control @error('name') is-invalid @enderror">

                        @error('name')
                        <div class="invalid-feedback" style="display: block">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label>Email</label>
                        <input type="email" name="email" value="{{ old('email', $publisher->email) }}"
                            placeholder="Enter Email"
                            class="form-control @error('email') is-invalid @enderror">

                        @error('email')
                        <div class="invalid-feedback" style="display: block">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label>Phone Number</label>
                        <input type="tel" name="phone_number" value="{{ old('phone_number', $publisher->phone_number) }}"
                            placeholder="081xxxxxxxxx" pattern="[0-9]{10,14}"
                            class="form-control @error('phone_number') is-invalid @enderror">

                        @error('phone_number')
                        <div class="invalid-feedback" style="display: block">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label>Address</label>
                        <input type="text" name="address" value="{{ old('address', $publisher->address) }}"
                            placeholder="Enter Address"
                            class="form-control @error('address') is-invalid @enderror">

                        @error('address')
                        <div class="invalid-feedback" style="display: block">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                    <div class="d-flex justify-content-center">
                        <button class="btn btn-primary mr-1 btn-submit" type="submit"><i class="fa fa-paper-plane"></i>Submit</button>
                        <button class="btn btn-warning btn-reset" type="reset"><i class="fa fa-redo"></i>Reset</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

latihan_laravel-vue/library/resources/views/admin/publisher/index.blade.php
@extends('layouts.admin')
@section('header', 'Publisher')
@section('content')
<div class="row">
    <div class="col">
        <div class="card">
            <div class="card-header">
                <a href="{{route('publishers.create')}}" class="btn btn-primary btn-sm">Add New Publisher</a>
            </div>
            <div class="card-body p-0">
                <table class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th class="text-center" style="width: 10px">#</th>
                            <th class="text-center">Name</th>
                            <th class="text-center">Email</th>
                            <th class="text-center">Phone</th>
                            <th class="text-center">Address</th>
                            <th class="text-center">Total Books</th>
                            <th class="text-center">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($publishers as $key => $publisher)
                        <tr>
                            <td>{{$key+1}}</td>
                            <td>{{$publisher->name}}</td>
                            <td>{{$publisher->email}}</td>
                            <td>{{$publisher->phone_number}}</td>
                            <td>{{$publisher->address}}</td>
                            <td>{{count($publisher->books)}}</td>
                            <td class="text-center">
                                <div class=" d-flex justify-content-center">
                                    <a href="{{ route('publishers.edit', $publisher->id) }}"
                                        class="btn btn-sm btn-primary mr-2">
                                        <i class="fa fa-pencil-alt"></i>
                                    </a>
                                    <button onClick="Delete(this.id)" class="btn btn-sm btn-danger"
                                        id="{{ $publisher->id }}">
                                        <i class="fa fa-trash"></i>
                                    </button>
                                </div>
                            </td>
                        </tr>
                        @endforeach

                    </tbody>
                </table>
            </div>

        </div>
    </div>
</div>
@endsection

@section('js')
<script>
    //ajax delete
    function Delete(id) {
        var id = id;
        var token = $("meta[name='csrf-token']").attr("content");
        swal({
            title: "Are You Sure?",
            text: "All Books With This Publisher Will Be Deleted!",
            icon: "warning",
            buttons: [
                'Cancel',
                'Yes, Delete It!'
            ],
            dangerMode: true,
        }).then(function(isConfirm) {
            if (isConfirm) {
                //ajax delete
                jQuery.ajax({
                    url: "{{url('publishers')}}/" + id,
                    data: {
                        "id": id,
                        "_token": token
                    },
                    type: 'DELETE',
                    success: function(response) {
                        if (response.status == "success") {
                            swal({
                                title: 'DELETED!',
                                text: 'Your Data Has Been Deleted!',
                                icon: 'success',
                                timer: 1000,
                                showConfirmButton: false,
                                showCancelButton: false,
                                buttons: false,
                            }).then(function() {
                                location.reload();
                            });
                        } else {
                            swal({
                                title: 'ERROR!',
                                text: 'Your Data Is Not Deleted!',
                                icon: 'error',
                                timer: 1000,
                                showConfirmButton: false,
                                showCancelButton: false,
                                buttons: false,
                            }).then(function() {
                                location.reload();
                            });
                        }
                    }
                });
            } else {
                return true;
            }
        })
    }
</script>
@endsection