latihan_laravel-vue/library/routes/web.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
})->middleware('guest');

Auth::routes();

Route::group(['middleware' => 'auth'], function () {
    Route::get('/home', [AdminController::class, 'index']);

    Route::resource('/authors', AuthorController::class);
    Route::resource('/books', BookController::class);
    Route::resource('/catalogs', CatalogController::class);
    Route::resource('/members', MemberController::class);
    Route::resource('/publishers', PublisherController::class);
    Route::resource('/transactions', TransactionController::class);

    Route::get('/api/authors', [AuthorController::class, 'api']);
    Route::get('/api/publishers', [PublisherController::class, 'api']);
    Route::get('/api/members', [MemberController::class, 'api']);
    Route::get('/api/books', [BookController::class, 'api']);
    Route::get('/api/transactions', [TransactionController::class, 'api']);

    Route::get('/test_spatie', [AdminController::class, 'test_spatie']);
});

latihan_laravel-vue/library/app/Http/Controllers/TransactionController.php
<?php

namespace App\Http\Controllers;

use App\Models\Book;
use App\Models\Member;
use App\Models\Transaction;
use App\Models\TransactionDetail;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;

class TransactionController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        return view('admin.transaction.index');
    }

    public function api(Request $request)
    {
        $status = $request->status;
        $date_start = $request->date_start;

        if ($status == '0' || $status == '1') {
            $transaction = Transaction::with('member', 'transactionDetails')
                ->orderBy('transactions.status', 'ASC')
                ->orderBy('transactions.id', 'DESC')
                ->where('transactions.status', $status)
                ->get();
        } else if ($date_start) {
            $transaction = Transaction::with('member', 'transactionDetails')
                ->orderBy('transactions.status', 'ASC')
                ->orderBy('transactions.id', 'DESC')
                ->whereRaw('MONTH(transactions.date_start) = ' . $date_start)
                ->get();
        } else {
            $transaction = Transaction::with('member', 'transactionDetails')
                ->orderBy('transactions.status', 'ASC')
                ->orderBy('transactions.id', 'DESC')
                ->get();
        }

        $dataTables = datatables()->of($transaction)
            ->addColumn('borrowing_time', function ($transaction) {
                $date_start = Carbon::parse($transaction->date_start);
                $date_end = Carbon::parse($transaction->date_end);
                $days = $date_start->diffInDays($date_end);
                return convert_days($days);
            })
            ->addColumn('total_books', function ($transaction) {
                return $transaction->transactionDetails->sum('qty');
            })
            ->addColumn('total_price', function ($transaction) {
                $price = 0;
                foreach ($transaction->transactionDetails as $transactionDetails) {
                    $price += $transactionDetails->book->price;
                }
                return convert_price($price);
            })
            ->editColumn('status', function ($transaction) {
                return $transaction->status == '0' ? "Borrowing" : "Returned";
            })
            ->addIndexColumn();

        return $dataTables->make(true);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $members = Member::all();
        $books = Book::where('qty', '!=', 0)->get();
        return view('admin.transaction.create', compact('members', 'books'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $request->validate([
            'member_id'  => 'required|numeric',
            'date_start'  => 'required|date',
            'date_end'  => 'required|date',
            'books_id.*'  => 'required|numeric',
        ]);

        $transaction = Transaction::create([
            'member_id'   => $request->member_id,
            'date_start'   => $request->date_start,
            'date_end'   => $request->date_end,
            'status' => '0',
        ]);

        foreach ($request->books_id as $book_id) {
            TransactionDetail::create([
                'transaction_id' => $transaction->id,
                'book_id' => $book_id,
                'qty' => 1,
            ]);

            $book = Book::find($book_id);
            $book->update([
                'qty' => $book->qty - 1,
            ]);
        }

        if ($transaction) {
            return redirect()->route('transactions.index')->with(['success' => 'Data Saved Successfully!']);
        } else {
            return redirect()->route('transactions.index')->with(['error' => 'Data Failed to Save!']);
        }
    }

    /**
     * Display the specified resource.
     */
    public function show(Transaction $transaction)
    {
        $transaction_details = TransactionDetail::whereRaw('transaction_id = ' . $transaction->id)->with('book')->get();
        $member = Member::find($transaction->member_id);
        return view('admin.transaction.show', compact('transaction', 'transaction_details', 'member'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Transaction $transaction)
    {
        $members = Member::all();
        $books = Book::where('qty', '!=', 0)->get();
        $selectedBooks = TransactionDetail::selectRaw('book_id')->whereRaw('transaction_id = ' . $transaction->id)->get();

        if ($transaction->status == '1') {
            return redirect()->route('transactions.index')->with(['success' => 'Book Have Been Returned!']);
        } else {
            return view('admin.transaction.edit', compact('transaction', 'members', 'books', 'selectedBooks'));
        }
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Transaction $transaction)
    {
        $request->validate([
            'member_id'  => 'required|numeric',
            'date_start'  => 'required|date',
            'date_end'  => 'required|date',
            'books_id.*'  => 'required|numeric',
            'status' =>
            [
                'required',
                Rule::in(['0', '1']),
            ],
        ]);

        $transaction->update([
            'member_id'   => $request->member_id,
            'date_start'   => $request->date_start,
            'date_end'   => $request->date_end,
            'status'   => $request->status,
        ]);

        if ($request->status == '0') {
            $transaction_details = TransactionDetail::whereRaw('transaction_id = ' . $transaction->id)->get();
            foreach ($transaction_details as $td) {
                $book = Book::find($td->book_id);
                $book->update([
                    'qty' => $book->qty + 1,
                ]);

                $td->delete();
            };

            foreach ($request->books_id as $book_id) {
                TransactionDetail::create([
                    'transaction_id' => $transaction->id,
                    'book_id' => $book_id,
                    'qty' => 1,
                ]);

                $book = Book::find($book_id);
                $book->update([
                    'qty' => $book->qty - 1,
                ]);
            };
        } else {
            $transaction_details = TransactionDetail::whereRaw('transaction_id = ' . $transaction->id)->get();
            foreach ($transaction_details as $td) {
                $book = Book::find($td->book_id);
                $book->update([
                    'qty' => $book->qty + 1,
                ]);
            };
        }

        if ($transaction) {
            return redirect()->route('transactions.index')->with(['success' => 'Data Updated Successfully!']);
        } else {
            return redirect()->route('transactions.index')->with(['error' => 'Data Failed to Update!']);
        }
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Transaction $transaction)
    {
        $transaction_details =  TransactionDetail::whereRaw('transaction_id = ' . $transaction->id)->get();
        foreach ($transaction_details as $td) {
            $book = Book::find($td->book_id);
            $book->update([
                'qty' => $book->qty + 1,
            ]);
        }

        $transaction->delete();


        if ($transaction) {
            return response()->json([
                'status' => 'success'
            ]);
        } else {
            return response()->json([
                'status' => 'error'
            ]);
        }
    }
}

latihan_laravel-vue/library/resources/views/admin/transaction/create.blade.php
@extends('layouts.admin')
@section('header', 'Transaction')
@section('css')
<!-- Select2 -->
<link rel="stylesheet" href="{{asset('assets/plugins/select2/css/select2.min.css') }}">
<link rel="stylesheet" href="{{asset('assets/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css') }}">
<!-- Theme style -->
<link rel="stylesheet" href="{{asset('assets/dist/css/adminlte.min.css') }}">
@endsection
@section('content')
<div class="row">
    <div class="col">
        <div class="card border-0 shadow">
            <div class="card-header">
                <h6 class="m-0 font-weight-bold"><i class="fas fa-plus mr-2"></i>Add Transaction</h6>
            </div>

            <div class="card-body">
                <form action="{{ route('transactions.store') }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <div class="form-group row">
                        <label class="col-md-4 col-form-label">Member</label>
                        <div class="col-md-8">
                            <select class="form-select @error('member_id') is-invalid @enderror" name="member_id" required>
                                <option value="" selected disabled>Select Member</option>
                                @foreach ($members as $member )
                                <option value="{{ $member->id }}">{{ $member->name }}</option>
                                @endforeach
                            </select>
                            @error('member_id')
                            <div class="invalid-feedback" style="display: block">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-md-4 col-form-label">Date Borrow</label>
                        <div class="col-md-8">
                            <div class="d-flex justify-content-between">
                                <input type="date" name="date_start"
                                    class="form-control col-5 @error('date_start') is-invalid @enderror" required>
                                <span class="col-2 text-center">&#8722;</span>
                                <input type="date" name="date_end"
                                    class="form-control col-5 @error('date_end') is-invalid @enderror" required>
                            </div>
                            @error('date_start')
                            <div class="invalid-feedback" style="display: block">
                                {{ $message }}
                            </div>
                            @enderror
                            @error('date_end')
                            <div class="invalid-feedback" style="display: block">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-md-4 col-form-label">Books</label>
                        <div class="col-md-8">
                            <select class="select2 @error('books_id') is-invalid @enderror" multiple="multiple" name="books_id[]" style="width: 100%;" required>
                                @foreach ($books as $book )
                                <option value="{{ $book->id }}">{{ $book->title }}</option>
                                @endforeach
                            </select>
                            @error('books_id')
                            <div class="invalid-feedback" style="display: block">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                    </div>
                    <div class="d-flex justify-content-end">
                        <button class="btn btn-primary mr-1 btn-submit" type="submit"><i class="fa fa-paper-plane"></i>Submit</button>
                        <a class="btn btn-secondary" href="{{route('transactions.index')}}"><i class="fa fa-times"></i>Cancel</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection
@section('js')
<!-- Select2 -->
<script src="{{ asset('assets/plugins/select2/js/select2.full.min.js') }}"></script>
<script>
    $(function() {
        //Initialize Select2 Elements
        $('.select2').select2({
            placeholder: 'Select Books',
        });
    });
</script>
@endsection

latihan_laravel-vue/library/resources/views/admin/transaction/edit.blade.php
@extends('layouts.admin')
@section('header', 'Transaction')
@section('css')
<!-- Select2 -->
<link rel="stylesheet" href="{{asset('assets/plugins/select2/css/select2.min.css') }}">
<link rel="stylesheet" href="{{asset('assets/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css') }}">
<!-- Theme style -->
<link rel="stylesheet" href="{{asset('assets/dist/css/adminlte.min.css') }}">
@endsection
@section('content')
<div class="row" id="controller">
    <div class="col">
        <div class="card border-0 shadow">
            <div class="card-header">
                <h6 class="m-0 font-weight-bold"><i class="fas fa-pencil-alt mr-2"></i>Edit Transaction</h6>
            </div>

            <div class="card-body">
                <form action="{{ route('transactions.update', $transaction->id) }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <input type="hidden" name="_method" value="PUT">
                    <div class="form-group row">
                        <label class="col-md-4 col-form-label">Member</label>
                        <div class="col-md-8">
                            <select class="form-select  @error('member_id') is-invalid @enderror" name="member_id" :value="{{$transaction->member_id}}" required>
                                <option value="" disabled>Select Member</option>
                                @foreach ($members as $member )
                                <option value="{{ $member->id }}">{{ $member->name }}</option>
                                @endforeach
                            </select>
                            @error('member_id')
                            <div class="invalid-feedback" style="display: block">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-md-4 col-form-label">Date Borrow</label>
                        <div class="col-md-8">
                            <div class="d-flex justify-content-between">
                                <input type="date" name="date_start"
                                    class="form-control col-5 @error('date_start') is-invalid @enderror" value="{{$transaction->date_start}}" required>
                                <span class="col-2 text-center">&#8722;</span>
                                <input type="date" name="date_end"
                                    class="form-control col-5 @error('date_end') is-invalid @enderror" value="{{$transaction->date_end}}" required>
                            </div>
                            @error('date_start')
                            <div class="invalid-feedback" style="display: block">
                                {{ $message }}
                            </div>
                            @enderror
                            @error('date_end')
                            <div class="invalid-feedback" style="display: block">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-md-4 col-form-label">Books</label>
                        <div class="col-md-8">
                            <select class="select2 @error('books_id') is-invalid @enderror" multiple="multiple" name="books_id[]" style="width: 100%;" required>
                                @foreach ($books as $book )
                                <option value="{{ $book->id }}">{{ $book->title }}</option>
                                @endforeach
                            </select>
                            @error('books_id')
                            <div class="invalid-feedback" style="display: block">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-md-4 col-form-label">Status</label>
                        <div class="col-md-8">
                            <div class="form-check">
                                <input class="form-check-input @error('status') is-invalid @enderror" type="radio" name="status" value="0" :checked="{{$transaction->status}} == '0'" />
                                <label class="form-check-label">Borrowing</label>
                            </div>
                            <div class="form-check">
                                <input class="form-check-input @error('status') is-invalid @enderror" type="radio" name="status" value="1" :checked="{{$transaction->status}} == '1'" />
                                <label class="form-check-label">Returned</label>
                            </div>
                            @error('status')
                            <div class="invalid-feedback" style="display: block">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                    </div>
                    <div class="d-flex justify-content-end">
                        <button class="btn btn-primary mr-1 btn-submit" type="submit"><i class="fa fa-paper-plane"></i>Submit</button>
                        <a class="btn btn-secondary" href="{{route('transactions.index')}}"><i class="fa fa-times"></i>Cancel</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@endsection
@section('js')
<!-- Select2 -->
<script src="{{ asset('assets/plugins/select2/js/select2.full.min.js') }}"></script>
<script>
    var apiUrl = '<?= url('api/selectedBooks'); ?>';

    var selectedBooks = <?php echo json_encode($selectedBooks); ?>;

    var dataSelected = selectedBooks.map(function(data) {
        return data.book_id;
    })

    $(function() {
        //Initialize Select2 Elements
        $('.select2').val(dataSelected).select2({
            placeholder: 'Select Books',
        });
    });

    var controller = new Vue({
        el: '#controller',
        data: {},

        methods: {},
        mounted: function() {},
    });
</script>
@endsection

latihan_laravel-vue/library/resources/views/admin/transaction/index.blade.php
@extends('layouts.admin')
@section('header', 'Transaction')
@section('css')
<!-- DataTables -->
<link rel="stylesheet" href="{{ asset('assets/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css') }}">
<link rel="stylesheet" href="{{ asset('assets/plugins/datatables-responsive/css/responsive.bootstrap4.min.css') }}">
<link rel="stylesheet" href="{{ asset('assets/plugins/datatables-buttons/css/buttons.bootstrap4.min.css') }}">
@endsection
@section('content')
<div id="controller">
    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-header row">
                    <div class="col d-flex justify-content-start">
                        <a href="{{route('transactions.create')}}" class="btn btn-primary btn-sm">Add Transaction</a>
                    </div>
                    <div class="col-4 d-flex justify-content-end">
                        <select name="status" class="form-select text-center col-6 mr-2">
                            <option value="9">Status Filter</option>
                            <option value="0">Borrowing</option>
                            <option value="1">Returned</option>
                        </select>
                        <select name="date_start" class="form-select text-center col-6">
                            <option value="0">Borrow Date Filter</option>
                            <option value="1"> January </option>
                            <option value="2"> February </option>
                            <option value="3"> March </option>
                            <option value="4"> April </option>
                            <option value="5"> May </option>
                            <option value="6"> June </option>
                            <option value="7"> July </option>
                            <option value="8"> Agustust </option>
                            <option value="9"> September </option>
                            <option value="10"> October </option>
                            <option value="11"> November </option>
                            <option value="12"> December </option>
                        </select>
                    </div>
                </div>
                <div class="container-fluid">
                    <div class="card-body p-2">
                        <table id="dataTable" class="table table-bordered table-striped w-100">
                            <thead>
                                <tr>
                                    <th class="text-center" style="width: 10px">#</th>
                                    <th class="text-center">Date Borrow</th>
                                    <th class="text-center">Date Return</th>
                                    <th class="text-center">Name</th>
                                    <th class="text-center">Borrowing Time<br />(Days)</th>
                                    <th class="text-center">Total Books</th>
                                    <th class="text-center">Total Price</th>
                                    <th class="text-center">Status</th>
                                    <th class="text-center">Action</th>
                                </tr>
                            </thead>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('js')
<!-- DataTables  & Plugins -->
<script src="{{ asset('assets/plugins/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('assets/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('assets/plugins/datatables-responsive/js/dataTables.responsive.min.js') }}"></script>
<script src="{{ asset('assets/plugins/datatables-responsive/js/responsive.bootstrap4.min.js') }}"></script>
<script src="{{ asset('assets/plugins/datatables-buttons/js/dataTables.buttons.min.js') }}"></script>
<script src="{{ asset('assets/plugins/datatables-buttons/js/buttons.bootstrap4.min.js') }}"></script>
<script src="{{ asset('assets/plugins/jszip/jszip.min.js') }}"></script>
<script src="{{ asset('assets/plugins/pdfmake/pdfmake.min.js') }}"></script>
<script src="{{ asset('assets/plugins/pdfmake/vfs_fonts.js') }}"></script>
<script src="{{ asset('assets/plugins/datatables-buttons/js/buttons.html5.min.js') }}"></script>
<script src="{{ asset('assets/plugins/datatables-buttons/js/buttons.print.min.js') }}"></script>
<script src="{{ asset('assets/plugins/datatables-buttons/js/buttons.colVis.min.js') }}"></script>

<!-- Yajra DataTables -->
<script type="text/javascript">
    var actionUrl = '<?= url('transactions'); ?>';
    var apiUrl = '<?= url('api/transactions'); ?>';

    var columns = [{
            data: 'DT_RowIndex',
            class: 'text-center',
            orderable: true
        },
        {
            data: 'date_start',
            class: 'text-center',
            orderable: true
        },
        {
            data: 'date_end',
            class: 'text-center',
            orderable: true
        },
        {
            data: 'member.name',
            class: 'text-center',
            orderable: true
        },
        {
            data: 'borrowing_time',
            class: 'text-center',
            orderable: false
        },
        {
            data: 'total_books',
            class: 'text-center',
            orderable: false
        },
        {
            data: 'total_price',
            class: 'text-center',
            orderable: false
        },
        {
            data: 'status',
            class: 'text-center',
            orderable: true
        },
        {
            render: function(index, row, data, meta) {
                return `
                <div class=" d-flex justify-content-center">
                <a href="{{url('/transactions/${data.id}')}}" class="btn btn-info btn-sm mr-2"><i class="fa fa-search"></i></a>
                <a href="{{url('/transactions/${data.id}/edit')}}" class="btn btn-warning btn-sm mr-2"><i class="fa fa-pencil-alt"></i></a>
                <button href="#" class="btn btn-danger btn-sm" onclick="controller.deleteData(event, ${data.id})"><i class="fa fa-trash"></i></button>
                </div>
                `;
            },
            class: 'text-center',
            orderable: false
        },
    ];

    var controller = new Vue({
        el: '#controller',
        data: {
            datas: [],
            data: {},
            actionUrl,
            apiUrl,
        },

        methods: {
            dataTable() {
                const _this = this;
                _this.table = $('#dataTable').DataTable({
                    ajax: {
                        url: _this.apiUrl,
                        type: 'GET',
                    },
                    columns: columns,
                }).on('xhr', function() {
                    _this.datas = _this.table.ajax.json().data;
                });
            },
            deleteData(event, id) {
                event.preventDefault();
                const _this = this;
                swal({
                    title: "Are You Sure?",
                    text: "All Asociated With This Will Be Deleted!",
                    icon: "warning",
                    buttons: [
                        'Cancel',
                        'Yes, Delete It!'
                    ],
                    dangerMode: true,
                }).then(function(isConfirm) {
                    if (isConfirm) {
                        axios.post(this.actionUrl + '/' + id, {
                            _method: 'DELETE'
                        }).then(function(response) {
                            swal({
                                title: 'DELETED!',
                                text: 'Your Data Has Been Deleted!',
                                icon: 'success',
                                timer: 1000,
                                showConfirmButton: false,
                                showCancelButton: false,
                                buttons: false,
                            }).then(function() {
                                _this.table.ajax.reload();
                            });
                        }).catch(function(error) {
                            swal({
                                title: 'ERROR!',
                                text: error,
                                icon: 'error',
                                timer: 1000,
                                showConfirmButton: false,
                                showCancelButton: false,
                                buttons: false,
                            }).then(function() {
                                _this.table.ajax.reload();
                            });
                        });
                    } else {
                        swal("Cancelled", "Data is safe!", "error");
                    }
                })
            },
        },

        mounted: function() {
            this.dataTable();
        },
    });

    //Status Filter
    $('select[name=status]').on('change', function() {
        status = $('select[name=status]').val();
        console.log(status);
        if (status == 9) {
            controller.table.ajax.url(apiUrl).load();
            $('select[name=date_start]').val(0);
        } else {
            controller.table.ajax.url(apiUrl + '?status=' + status).load();
            $('select[name=date_start]').val(0);
        }
    });

    //Borrow Date Filter
    $('select[name=date_start]').on('change', function() {
        date_start = $('select[name=date_start]').val();
        if (date_start == 0) {
            controller.table.ajax.url(apiUrl).load();
            $('select[name=status]').val(9);
        } else {
            controller.table.ajax.url(apiUrl + '?date_start=' + date_start).load();
            $('select[name=status]').val(9);
        }
    });
</script>

@endsection