latihan_laravel-vue/library/routes/web.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
})->middleware('guest');

Auth::routes();

Route::group(['middleware' => 'auth'], function () {
    Route::get('/home', [AdminController::class, 'index']);

    Route::resource('/authors', AuthorController::class);
    Route::resource('/books', BookController::class);
    Route::resource('/catalogs', CatalogController::class);
    Route::resource('/members', MemberController::class);
    Route::resource('/publishers', PublisherController::class);
    Route::resource('/transactions', TransactionController::class);

    Route::get('/api/authors', [AuthorController::class, 'api']);
    Route::get('/api/publishers', [PublisherController::class, 'api']);
    Route::get('/api/members', [MemberController::class, 'api']);
    Route::get('/api/books', [BookController::class, 'api']);
    Route::get('/api/transactions', [TransactionController::class, 'api']);

    Route::get('/test_spatie', [AdminController::class, 'test_spatie']);
});

latihan_laravel-vue/library/app/Models/Catalog.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Catalog extends Model
{
    use HasFactory;

    protected $fillable = [
        'name'
    ];

    public function books()
    {
        return $this->hasMany(Book::class);
    }
}

latihan_laravel-vue/library/app/Http/Controllers/CatalogController.php
<?php

namespace App\Http\Controllers;

use App\Models\Catalog;
use Illuminate\Http\Request;

class CatalogController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $catalogs = Catalog::with('books')->get()->all();

        foreach ($catalogs as $key => $catalog) {
            $catalog->date = convert_date($catalog->created_at);
        }
        return view('admin.catalog.index', compact('catalogs'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('admin.catalog.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $request->validate([
            'name'  => 'required|unique:catalogs'
        ]);

        $catalog = Catalog::create([
            'name'   => $request->name,
        ]);

        if ($catalog) {
            return redirect()->route('catalogs.index')->with(['success' => 'Data Saved Successfully!']);
        } else {
            return redirect()->route('catalogs.index')->with(['error' => 'Data Failed to Save!']);
        }
    }

    /**
     * Display the specified resource.
     */
    public function show(Catalog $catalog)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Catalog $catalog)
    {
        return view('admin.catalog.edit', compact('catalog'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Catalog $catalog)
    {
        $request->validate([
            'name'  => 'required|unique:catalogs'
        ]);

        $catalog->update([
            'name'   => $request->name,
        ]);

        if ($catalog) {
            return redirect()->route('catalogs.index')->with(['success' => 'Data Updated Successfully!']);
        } else {
            return redirect()->route('catalogs.index')->with(['error' => 'Data Failed to Update!']);
        }
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Catalog $catalog)
    {
        $catalog->delete();

        if ($catalog) {
            return response()->json([
                'status' => 'success'
            ]);
        } else {
            return response()->json([
                'status' => 'error'
            ]);
        }
    }
}

latihan_laravel-vue/library/resources/views/admin/catalog/create.blade.php
@extends('layouts.admin')
@section('header', 'Catalog')
@section('content')
<div class="row">
    <div class="col">
        <div class="card border-0 shadow">
            <div class="card-header">
                <h6 class="m-0 font-weight-bold"><i class="fas fa-plus mr-2"></i>Create New Catalog</h6>
            </div>

            <div class="card-body">
                <form action="{{ route('catalogs.store') }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <div class="form-group">
                        <label>Name</label>
                        <input type="text" name="name" value="{{ old('name') }}"
                            placeholder="Enter Name"
                            class="form-control @error('name') is-invalid @enderror">

                        @error('name')
                        <div class="invalid-feedback" style="display: block">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                    <div class="d-flex justify-content-center">
                        <button class="btn btn-primary mr-1 btn-submit" type="submit"><i class="fa fa-paper-plane"></i>Submit</button>
                        <button class="btn btn-warning btn-reset" type="reset"><i class="fa fa-redo"></i>Reset</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

latihan_laravel-vue/library/resources/views/admin/catalog/edit.blade.php
@extends('layouts.admin')
@section('header', 'Catalog')
@section('content')
<div class="row">
    <div class="col">
        <div class="card border-0 shadow">
            <div class="card-header">
                <h6 class="m-0 font-weight-bold"><i class="fas fa-pencil-alt mr-2"></i>Edit Catalog</h6>
            </div>

            <div class="card-body">
                <form action="{{ route('catalogs.update', $catalog->id) }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    @method('PUT')
                    <div class="form-group">
                        <label>Name</label>
                        <input type="text" name="name" value="{{ old('name', $catalog->name) }}"
                            placeholder="Enter Name"
                            class="form-control @error('name') is-invalid @enderror">

                        @error('name')
                        <div class="invalid-feedback" style="display: block">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                    <div class="d-flex justify-content-center">
                        <button class="btn btn-primary mr-1 btn-submit" type="submit"><i class="fa fa-paper-plane"></i>Submit</button>
                        <button class="btn btn-warning btn-reset" type="reset"><i class="fa fa-redo"></i>Reset</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

latihan_laravel-vue/library/resources/views/admin/catalog/index.blade.php
@extends('layouts.admin')
@section('header', 'Catalog')
@section('content')
<div class="row">
    <div class="col">
        <div class="card">
            <div class="card-header">
                <a href="{{route('catalogs.create')}}" class="btn btn-primary btn-sm">Add New Catalog</a>
            </div>
            <div class="card-body p-0">
                <table class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th class="text-center" style="width: 10px">#</th>
                            <th class="text-center">Name</th>
                            <th class="text-center">Total Books</th>
                            <th class="text-center">Created At</th>
                            <th class="text-center">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($catalogs as $key => $catalog)
                        <tr>
                            <td class="text-center">{{$key+1}}</td>
                            <td class="text-center">{{$catalog->name}}</td>
                            <td class="text-center">{{count($catalog->books)}}</td>
                            <td class="text-center">{{$catalog->date}}</td>
                            <td class="text-center d-flex justify-content-center">
                                <a href="{{ route('catalogs.edit', $catalog->id) }}"
                                    class="btn btn-sm btn-primary mr-2">
                                    <i class="fa fa-pencil-alt"></i>
                                </a>
                                <button onClick="Delete(this.id)" class="btn btn-sm btn-danger"
                                    id="{{ $catalog->id }}">
                                    <i class="fa fa-trash"></i>
                                </button>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection

@section('js')
<script>
    //ajax delete
    function Delete(id) {
        var id = id;
        var token = $("meta[name='csrf-token']").attr("content");
        swal({
            title: "Are You Sure?",
            text: "All Books With This Catalog Will Be Deleted!",
            icon: "warning",
            buttons: [
                'Cancel',
                'Yes, Delete It!'
            ],
            dangerMode: true,
        }).then(function(isConfirm) {
            if (isConfirm) {
                //ajax delete
                jQuery.ajax({
                    url: "{{url('catalogs')}}/" + id,
                    data: {
                        "id": id,
                        "_token": token
                    },
                    type: 'DELETE',
                    success: function(response) {
                        if (response.status == "success") {
                            swal({
                                title: 'DELETED!',
                                text: 'Your Data Has Been Deleted!',
                                icon: 'success',
                                timer: 1000,
                                showConfirmButton: false,
                                showCancelButton: false,
                                buttons: false,
                            }).then(function() {
                                location.reload();
                            });
                        } else {
                            swal({
                                title: 'ERROR!',
                                text: 'Your Data Is Not Deleted!',
                                icon: 'error',
                                timer: 1000,
                                showConfirmButton: false,
                                showCancelButton: false,
                                buttons: false,
                            }).then(function() {
                                location.reload();
                            });
                        }
                    }
                });
            } else {
                return true;
            }
        })
    }
</script>
@endsection